server:
  port: 8081

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ahu264657
  dbname: hmdp

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: password123

jwt:
  secret: JtrQN0N0roqldXHHrxxp3x7TEmlWorIBOcRSvULpT4d  # 密钥
  expire: 3600  # 令牌过期时间，单位为秒，这里设置为1小时